### PR TITLE
Fixed #395. Also, updated dist build components

### LINKED ISSUE #395: Segfaults on broken UTF
Right after start,  wcm crashes. Seems like this happens when filename in broken utf is encountered.

```
(gdb) run
Starting program: /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/stage/home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/prefix/bin/wcm 
[New Thread 805406400 (LWP 100960)]
[New Thread 805406c00 (LWP 101135)]
[New Thread 80540e400 (LWP 101555)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 80540e400 (LWP 101555)]
strlen (str=0x0) at /usr/src/lib/libc/string/strlen.c:100
100		va = (*lp - mask01);
(gdb) bt
#0  strlen (str=0x0) at /usr/src/lib/libc/string/strlen.c:100
#1  0x00000000005d20cf in length (__s=<optimized out>, __s=<optimized out>) at /usr/include/c++/v1/string:651
#2  basic_string (this=<optimized out>, __s=<optimized out>, this=<optimized out>, __s=<optimized out>) at /usr/include/c++/v1/string:1866
#3  wal::normalize_utf8_NFC (Str=0x7fffdf7f9810 "pixel-gif-\320\277\320\276\320\263\320\276\320\275\321%8F-1343735.gif")
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/wal/wal.cpp:488
#4  0x00000000005c2e58 in FSSys::ReadDir (this=0x8063ffee0, list=0x806812880, _path=..., err=0x7fffdf7f9c70, info=0x7fffdf7f9d58)
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/vfs.cpp:1317
#5  0x0000000000454d9c in OperRDThread::Run (this=0x7fffdf7f9d28)
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/fileopers.cpp:240
#6  0x00000000004553e3 in ReadDirThreadFunc (node=0x8054761d0)
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/fileopers.cpp:292
#7  0x0000000000500910 in OperThreadParam::RunFunc (this=0x8063ffe40)
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/operwin.cpp:89
#8  0x00000000004ffcf9 in __123___OperThread (param=0x8063ffe40)
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/operwin.cpp:105
#9  0x000000000055f48c in wal::_swl_win_thread_func (data=0x8055b45b0)
    at /home/amdmi3/projects/freebsd/batchports-mem/x11-fm/walcommander/work/corporateshark-WalCommander-000e93b/src/swl/swl_wincore.cpp:709
#10 0x0000000802434585 in thread_start (curthread=0x80540e400) at /usr/src/lib/libthr/thread/thr_create.c:284
#11 0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdf7fa000
```

### PR DESCRIPTION
**Pull request by helgp**
My test case of #395 was still failing after the commit  7b8ff0d. It did pass with the fix below. 

Note that this is palliative fix. Wcm now shows empty string instead on broken UTF8 filename. It is better to follow standard approach to show '?' mark in place of bad UTF symbol, and allow user to handle file with the broken name in some way.

### CODE REVIEW

File: src/wal/wal.cpp [hunk 1]
```diff
@@ -484,6 +484,8 @@ namespace wal
 #if !defined(_WIN32)
 		uint8_t* NormString = utf8proc_NFC( (const uint8_t*)Str );
 
+		if(!NormString) return std::string();
```
Comment (corporateshark) [inline src/wal/wal.cpp]: Should return original ``Str``, this was the original behavior.
